name: SonarQube Cloud Analysis
on:
  push:
    branches:
      - main # Sadece ana dala kod geldiğinde tetiklenir
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up GraalVM/Java 26
        uses: actions/setup-java@v4
        with:
          java-version: '26'
          distribution: 'temurin'
          cache: maven
          
      - name: Cache SonarCloud Packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Yan dallarda (PR aşamasında) sadece standart 'mvn clean verify' koşacak, Sonar'ı zorlamayacak.
      - name: Build and Run Tests with JaCoCo Coverage
        working-directory: byz-quant-fed-service
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Sadece temiz 'mvn clean verify sonar:sonar' koşturuyoruz. 
        # JaCoCo 0.8.15 zaten raporu basacak, Sonar da otomatik yakalayacak!
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=byzquant_fed-service \
            -Dsonar.organization=byz-labs \
            -Dsonar.host.url=https://sonarcloud.io
